### ISSUE TITLE
Divide main content

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#10]
Divide main content into two columns:

![image](https://user-images.githubusercontent.com/11459051/30785533-9e364ef0-a170-11e7-86ef-30ce18e19773.png)

1-2 should have the same background color, outside 1-2 blocks should be a white page.

**Comment by i10111pn** [comment]
In general, your page should look like this:

![image](https://user-images.githubusercontent.com/11459051/30930722-36358a02-a3cb-11e7-95b9-b704de513616.png)

**Comment by IvanKhud** [comment]
done
