### ISSUE TITLE
Add small screen support

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#12]
For screens smaller than 768px
http://getbootstrap.com/css/#grid (Extra small devices)

The page should look next

![image](https://user-images.githubusercontent.com/11459051/30785558-0c511ba4-a171-11e7-89c1-6fe3e9f11334.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
On small screen logo alignment is incorrect: 

![image](https://user-images.githubusercontent.com/11459051/31224180-91941520-a9d5-11e7-8a0b-aa2a63380994.png)

**Comment by i10111pn** [comment]
Small screen is not fully supported, there is should not be horizontal scroll (see 1 in picture)
As result user, can't see 'Go to top/bottom' navigation (see 2 in picture)

![image](https://user-images.githubusercontent.com/11459051/31224432-8a10b14a-a9d6-11e7-8f61-a54d449d4a78.png)

**Comment by IvanKhud** [comment]
fixed
