### ISSUE TITLE
Rework blocks

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#13]
Rework your blocks like this:

![image](https://user-images.githubusercontent.com/11459051/30964693-2f9d8b46-a45b-11e7-93fa-aa41623351b3.png)

1. Make header full width.
2. Make main content wider.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Align header and make the main container wider:
![image](https://user-images.githubusercontent.com/11459051/31058761-935ae342-a701-11e7-99c4-7932dc6b9119.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
The header is not aligned:

![image](https://user-images.githubusercontent.com/11459051/31058829-3e04c06e-a703-11e7-8608-580a273531f5.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Could not see this at Heroku.


![image](https://user-images.githubusercontent.com/11459051/31080615-df11edf4-a791-11e7-8cd5-6013f0d974e0.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
The logo is not aligned properly.
The distance between main block and statistic block is too big.

![image](https://user-images.githubusercontent.com/11459051/31224597-4568146a-a9d7-11e7-8b00-4afd6d834fff.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Set statistic block to full width on small screens:

![image](https://user-images.githubusercontent.com/11459051/31251711-99012526-aa27-11e7-9d4a-1184305a6504.png)

**Comment by IvanKhud** [comment]
done
