### ISSUE TITLE
Disable pagination's buttons

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#14]
1. On starting position the `First` button should be disabled (its already showing rows from the first row)
Also, in this case, the `Previous` button should become disabled too.

2. After clicking on the `Last` button it should become disabled. Also, in this case, the `Next ` button should become disabled too.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Could you please check if your changes are deployed on Heroku?

**Comment by IvanKhud** [comment]
yes, it already deployed. I also did not see changes immediately, only after ctrl+F5

**Comment by i10111pn** [comment]
A disabled button should change the cursor on hover.
See example here:

https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_active&stacked=h

**Comment by IvanKhud** [comment]
but in this case it only changes cursor, click events on it are still available. 
i used CSS rule: .disabled {pointer-events:none} to prevent this

**Comment by i10111pn** [comment]
add to your css rule cursor property
https://www.w3schools.com/cssref/tryit.asp?filename=trycss_cursor

**Comment by IvanKhud** [comment]
tried it, the same problem. When there is a rule pointer-events:none, there are no cursor.
If i remove it, button is clickable. You can try it there, add onclick="alert(123)" to disabled button and you will see: https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_active&stacked=h

**Comment by i10111pn** [comment]
Try to add `disabled ` attribute
![image](https://user-images.githubusercontent.com/11459051/30968417-ec0e1aaa-a467-11e7-8655-b1d887b94fc9.png)

**Comment by IvanKhud** [comment]
tried. this method doesn't work with pagination's <li> elements

**Comment by i10111pn** [comment]
Set cursor property to the parent element (li)
Example:
html:
```
<li>
  <a href="link.html" class="disabled" onclick="alert(1)">Link</a>
</li>
```

css:

```
li {
  cursor: not-allowed;
}

.disabled {
  pointer-events: none;
  } 
```
