### ISSUE TITLE
Add ability to Reset application

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#15]
1. Rename the `Run ` button to `Start`

2. After clicking on the `Start `button it should change name to `Reset`

3. By click on the `Reset `button it should reset the application to the initial state, like when you press F5 button.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
The `Reset`  button does not set the application to the initial state.
This is initial state:

![image](https://user-images.githubusercontent.com/11459051/30990439-ed46f18e-a4a9-11e7-8248-f9449bc50076.png)

Now select to show 10 rows per page and click on the `Reset` button.
The result is this:
![image](https://user-images.githubusercontent.com/11459051/30990488-1c7a2782-a4aa-11e7-93a5-59604f9c6b66.png)

**Comment by IvanKhud** [comment]
fixed

**Comment by i10111pn** [comment]
After click on the `Reset ` button, I see:
![image](https://user-images.githubusercontent.com/11459051/30991792-3fcdc7ca-a4af-11e7-8a34-c4805ca0ccbe.png)

But the initial state of the application is this:
![image](https://user-images.githubusercontent.com/11459051/30991824-6badd0d8-a4af-11e7-9e67-3f326efd222c.png)

Initial state means how the application looks just after loading.
In other words - after click on the `Reset` button you should see the same when you opened the application.

**Comment by IvanKhud** [comment]
In this case, we don't need 'Start' butoon, because: 1) in initial state the button caption is 'Reset'; 2) in initial state all elements is available, and we don't need to use 'Start' button for anything.
So, i see 2 solutions: a) make a program look on startup like now it looks after resetting or b) delete 'Start' button and leave only 'Reset'.

**Comment by i10111pn** [comment]
Do as you described in the 'a' option.

**Comment by IvanKhud** [comment]
done
