### ISSUE TITLE
Add ability to select starting row

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#18]
Example:
I choose to show 10 rows per page and start from row 110

![image](https://user-images.githubusercontent.com/11459051/31016768-aa7f2a94-a52e-11e7-937a-00b3b79ebeee.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
After pressing `Start` button there is some red area (I think it is error message area)

![image](https://user-images.githubusercontent.com/11459051/31124253-49faeb2e-a84c-11e7-9783-5460c6461494.png)

Fix this
