### ISSUE TITLE
Add navigation buttons

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#19]
If the page has scroll.
Add buttons, that scrolls page to the page top/bottom.

See example here.
Here is only "go to the top" example.
https://codepen.io/rdallaire/pen/apoyx

Don't be confused by code, just see the example.

**Comment by IvanKhud** [comment]
Added buttons. Currently the function that has to hide "to bottom" button is not working yet. "to top" button is working fine. I also have not yet completed the look of the buttons.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Finish with styling. Also, check this case:
Select to show all rows.
Note, that 'go to bottom/top' buttons not appearing immediately.

**Comment by IvanKhud** [comment]
button appearing on scroll.

**Comment by i10111pn** [comment]
I know. But they should appear immediately after scroll became visible.

**Comment by IvanKhud** [comment]
now buttons appearing immediately after appearing scroll

**Comment by i10111pn** [comment]
Could not see this at Heroku.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
it is not working on after the first scroll appearance

**Comment by IvanKhud** [comment]
fixed

**Comment by i10111pn** [comment]
'Go to bottom' is not working (actually it is working like 'go to top')

**Comment by i10111pn** [comment]
Merge this to button into one.
And make it looks like this:

![image](https://user-images.githubusercontent.com/11459051/31059426-9900b17e-a70a-11e7-92b9-a27e8031ed7b.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Change color of arrows. 
Currently they almost invisible.

**Comment by IvanKhud** [comment]
done
