### ISSUE TITLE
'Start display from input' behavior

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#21]
`Start display from` input always should show starting number.

 After pressing `Start` button it should show '1':

![image](https://user-images.githubusercontent.com/11459051/31134802-d75d673e-a86b-11e7-9cc7-c87112e63072.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Press `Start` button and then press `Last` button:

![image](https://user-images.githubusercontent.com/11459051/31139418-2a83655e-a87a-11e7-9c76-2a72becfa83c.png)

`Start display from` input show 1 instead 96

**Comment by IvanKhud** [comment]
fixed
