### ISSUE TITLE
Change initial state of the application

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#22]
Set the initial state of the application to this:

![image](https://user-images.githubusercontent.com/11459051/31134869-09e7f3ae-a86c-11e7-8fa5-6e2aed13f584.png)

After pressing `Reset` button the state should be:

![image](https://user-images.githubusercontent.com/11459051/31135001-6f47c35a-a86c-11e7-87ce-3a4f36a858af.png)

**Comment by IvanKhud** [comment]
done
