### ISSUE TITLE
'Reset' button behavior

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#24]
**Steps to reproduce:**

1. Enter 10 into `Start display from` input
2. Press 'Reset' button.
3. Press 'Start' button.

**Expected behavior:**
`Start display from` input display 1

**Current behavior:**
`Start display from` input display 10

![image](https://user-images.githubusercontent.com/11459051/31136501-1a2117fa-a871-11e7-9403-5323e07567e9.png)

**Comment by IvanKhud** [comment]
done
