### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#25]
**Steps to reproduce:**
1. Enter 0 (zero) in `Start display from` input.
2. Click outside the input.

**Expected behavior:**
'You can start from 1 only' error message appears

**Current behavior:**
'You can only enter a number' error message appears

![image](https://user-images.githubusercontent.com/11459051/31136869-13aeb7aa-a872-11e7-8bc7-7e8ce90f228a.png)

**Comment by IvanKhud** [comment]
fixed
