### ISSUE TITLE
Format your code, rename variables, classes

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#27]
For code formatting see https://github.com/airbnb/javascript/tree/es5-deprecated/es5

**Comment by IvanKhud** [comment]
moved all dom-related functions into dom class

**Comment by i10111pn** [comment]
Format all `if` statements to this:

```
if (condition) {
  /*code*/
} else {
  /*code*/
}
```

**Comment by i10111pn** [comment]
Do it in all js files.

**Comment by IvanKhud** [comment]
done
