### ISSUE TITLE
App enhancements

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#28]
**1.** Clicked pagination button should be blue.
See bootstrap 'btn-default' class:
http://getbootstrap.com/components/#btn-dropdowns-single

**2.** `Reset` button should be red.
See bootstrap 'btn-danger' class:
http://getbootstrap.com/components/#btn-dropdowns-single

**3.** CSS class names should be in named in format "word1-word2"
Example:
```
.headerContent {
  float: left;
  position: relative;
  margin: auto;
  margin-left: 80px;
  width: 520px;
  border: 1px solid #f7f7f9;
}
```
This class should be renamed to `.header-content`

4. Decrease distance between main block and statistic block to 5-10px:
![image](https://user-images.githubusercontent.com/11459051/31137977-8b146c56-a875-11e7-99ab-4707931a7512.png)

**Comment by IvanKhud** [comment]
done

**Comment by IvanKhud** [comment]
about pagination button: they are blue on default, adding btn-default class changes nothing.

**Comment by i10111pn** [comment]
Add a background color to clicked button.
The color of text, in this case, should be white.

![image](https://user-images.githubusercontent.com/11459051/31175121-cf5f8372-a916-11e7-8e7f-cc27c690dd54.png)

**Comment by IvanKhud** [comment]
done
