### ISSUE TITLE
Add headers to list

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/FirstJSApp#6]
Add list headers to your list.
Add 'Floor' and 'Attempts count'

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Remove "--->" and rework your list like this:

![image](https://user-images.githubusercontent.com/11459051/30809531-b7bd5d38-a20a-11e7-9b83-065f9e5a36ec.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Make your table narrower.
